import { expect, test } from '@playwright/test';
import { resolve } from 'node:path';

const archive = resolve(process.cwd(), '../fixtures/golden-v1.ibl-ephys-atlas.zip');
const authoredArchive = resolve(process.cwd(), '../fixtures/authored-regional-v1.ibl-ephys-atlas.zip');

async function openImport(page: import('@playwright/test').Page): Promise<void> {
  const dataset = page.locator('[data-context-field="dataset"]');
  await dataset.locator('.context-menu__trigger').click();
  await dataset.getByRole('option', { name: 'Import local dataset…' }).click();
}

async function importArchive(page: import('@playwright/test').Page, path: string): Promise<void> {
  await openImport(page);
  await page.locator('.local-import__input').setInputFiles(path);
  const dialog = page.getByRole('dialog', { name: 'Import local dataset' });
  await expect(dialog.getByRole('status')).toContainText('Validation complete');
  await dialog.getByRole('button', { name: 'Import', exact: true }).click();
  await expect(dialog).toBeHidden();
}

test('validated ZIP preview is read-only until confirmation and persists locally', async ({ page }) => {
  await page.goto('/');

  await openImport(page);
  const input = page.locator('.local-import__input');
  await expect(input).toHaveAttribute('accept', '.ibl-ephys-atlas.zip,application/zip');
  expect(await input.evaluate((node: HTMLInputElement) => ({ multiple: node.multiple, directory: 'webkitdirectory' in node && node.webkitdirectory })))
    .toEqual({ multiple: false, directory: false });
  await input.setInputFiles(archive);

  const dialog = page.getByRole('dialog', { name: 'Import local dataset' });
  await expect(dialog).toBeVisible();
  await expect(dialog.getByRole('status')).toContainText('Validation complete');
  await expect(dialog).toContainText('IBL Ephys Atlas v2 golden fixture');
  await expect(dialog).toContainText('golden_fixture');
  await expect(dialog).toContainText('golden-v1');
  await expect(dialog).toContainText('recipe golden-fixture-v1');
  await expect(dialog).toContainText('Regional, Volume');
  await expect(dialog).toContainText('Allen');

  const dataset = page.locator('[data-context-field="dataset"]');
  await expect(dataset.locator('.context-field__local-badge')).toBeHidden();
  await expect(dataset.locator('.context-field__value')).not.toContainText('Local datasets');

  await dialog.getByRole('button', { name: 'Import', exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(dataset.locator('.context-field__local-badge')).toBeVisible();
  await expect(page.locator('[data-context-field="feature"] .context-field__value')).toContainText('AP RMS');
  await expect(page.locator('.feature-summary')).toContainText('Observations11');
  await expect.poll(() => new URL(page.url()).searchParams.get('dataset')).toBe('local');
  await expect.poll(() => new URL(page.url()).searchParams.get('release')).toBe('golden_fixture@golden-v1');

  await page.route('**/__real-data/**', (route) => route.abort());
  await page.reload();
  await expect(dataset.locator('.context-field__local-badge')).toBeVisible();
  await expect(page.locator('[data-context-field="feature"] .context-field__value')).toContainText('AP RMS');
  await expect(page.locator('.feature-summary')).toContainText('Observations11');
});

test('duplicate immutable local releases are rejected without replacing the stored release', async ({ page }) => {
  await page.goto('/');
  await openImport(page);
  await page.locator('.local-import__input').setInputFiles(archive);
  let dialog = page.getByRole('dialog', { name: 'Import local dataset' });
  await dialog.getByRole('button', { name: 'Import', exact: true }).click();
  await expect(dialog).toBeHidden();

  await openImport(page);
  await page.locator('.local-import__input').setInputFiles(archive);
  dialog = page.getByRole('dialog', { name: 'Import local dataset' });
  await dialog.getByRole('button', { name: 'Import', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('already imported');
  await dialog.getByRole('button', { name: 'Cancel' }).click();

  await page.reload();
  await expect(page.locator('[data-context-field="dataset"] .context-field__local-badge')).toBeVisible();
  await expect(page.locator('[data-context-field="feature"] .context-field__value')).toContainText('AP RMS');
  await expect(page.locator('.feature-summary')).toContainText('Observations11');
});

test('a bundle generated by the public regional authoring API imports through the real browser path', async ({ page }) => {
  await page.goto('/');
  await openImport(page);
  await page.locator('.local-import__input').setInputFiles(authoredArchive);
  const dialog = page.getByRole('dialog', { name: 'Import local dataset' });
  await expect(dialog).toContainText('Public authoring regional fixture');
  await expect(dialog).toContainText('decision_signal');
  await expect(dialog).toContainText('ibl-ephys-atlas-regional-authoring-v1');
  await dialog.getByRole('button', { name: 'Import', exact: true }).click();

  await expect(page.locator('[data-context-field="dataset"] .context-field__local-badge')).toBeVisible();
  await expect(page.locator('[data-context-field="feature"] .context-field__value')).toContainText('Decision signal');
  await expect(page.locator('.feature-summary')).toContainText('Observations4');
});

test('deleting the active local release is confirmed, atomic, isolated, and permits reimport', async ({ page }) => {
  await page.goto('/');
  await importArchive(page, archive);
  await importArchive(page, authoredArchive);

  const dataset = page.locator('[data-context-field="dataset"]');
  await dataset.locator('.context-menu__trigger').click();
  await dataset.getByRole('option', { name: 'Delete this local dataset…' }).click();
  let dialog = page.getByRole('dialog', { name: 'Delete local dataset' });
  await expect(dialog).toContainText('authored_regional_fixture@authored-regional-v1');
  await expect(dialog).toContainText('this browser on this device');
  await dialog.getByRole('button', { name: 'Cancel' }).click();
  await expect(dialog).toBeHidden();
  await expect(dataset.locator('.context-field__local-badge')).toBeVisible();

  await dataset.locator('.context-menu__trigger').click();
  await dataset.getByRole('option', { name: 'Delete this local dataset…' }).click();
  dialog = page.getByRole('dialog', { name: 'Delete local dataset' });
  await dialog.getByRole('button', { name: 'Delete local dataset' }).click();
  await expect(dialog).toBeHidden();
  await expect(dataset.locator('.context-field__local-badge')).toBeHidden();
  await expect.poll(() => new URL(page.url()).searchParams.get('dataset')).not.toBe('local');
  await expect.poll(() => new URL(page.url()).searchParams.get('release')).not.toBe('authored_regional_fixture@authored-regional-v1');

  const stored = await page.evaluate(async () => {
    const db = await new Promise<IDBDatabase>((resolve, reject) => {
      const request = indexedDB.open('ibl-ephys-atlas-schema-v1-local', 1);
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject(request.error);
    });
    const transaction = db.transaction(['manifests', 'resources'], 'readonly');
    const values = await Promise.all(['manifests', 'resources'].map((name) => new Promise<IDBValidKey[]>((resolve, reject) => {
      const request = transaction.objectStore(name).getAllKeys();
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject(request.error);
    })));
    db.close();
    return { manifests: values[0]!.map(String), resources: values[1]!.map(String) };
  });
  expect(stored.manifests).toEqual(['golden_fixture@golden-v1']);
  expect(stored.resources.some((key) => key.startsWith('authored_regional_fixture@authored-regional-v1\0'))).toBe(false);
  expect(stored.resources.some((key) => key.startsWith('golden_fixture@golden-v1\0'))).toBe(true);

  await page.goBack();
  await expect(dataset.locator('.context-field__local-badge')).toBeVisible();
  await expect.poll(() => new URL(page.url()).searchParams.get('release')).toBe('golden_fixture@golden-v1');
  await expect(page.locator('.feature-summary')).toContainText('Observations11');

  await importArchive(page, authoredArchive);
  await expect(page.locator('[data-context-field="feature"] .context-field__value')).toContainText('Decision signal');
});

test('sharing a local view discloses that the dataset is not transferred before copying', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(navigator, 'clipboard', {
      configurable: true,
      value: { writeText: async (value: string) => { (window as Window & { __copiedUrl?: string }).__copiedUrl = value; } },
    });
  });
  await page.goto('/');
  await importArchive(page, archive);

  const share = page.locator('.app-header__desktop-actions').getByRole('button', { name: 'Share' });
  await share.click();
  let dialog = page.getByRole('dialog', { name: 'Share local view' });
  await expect(dialog).toContainText('does not contain or transfer the dataset');
  await expect(dialog).toContainText('exact local release is already imported');
  expect(await page.evaluate(() => (window as Window & { __copiedUrl?: string }).__copiedUrl)).toBeUndefined();
  await dialog.getByRole('button', { name: 'Cancel' }).click();
  expect(await page.evaluate(() => (window as Window & { __copiedUrl?: string }).__copiedUrl)).toBeUndefined();

  await share.click();
  dialog = page.getByRole('dialog', { name: 'Share local view' });
  await dialog.getByRole('button', { name: 'Copy local link' }).click();
  await expect(dialog).toBeHidden();
  expect(await page.evaluate(() => (window as Window & { __copiedUrl?: string }).__copiedUrl)).toBe(page.url());
});

test('quota exhaustion aborts admission with actionable recovery guidance', async ({ page }) => {
  await page.addInitScript(() => {
    const originalPut = IDBObjectStore.prototype.put;
    IDBObjectStore.prototype.put = function (...args: Parameters<IDBObjectStore['put']>) {
      if (this.name === 'resources') throw new DOMException('Synthetic quota exhaustion', 'QuotaExceededError');
      return originalPut.apply(this, args);
    };
  });
  await page.goto('/');
  await openImport(page);
  await page.locator('.local-import__input').setInputFiles(archive);
  const dialog = page.getByRole('dialog', { name: 'Import local dataset' });
  await dialog.getByRole('button', { name: 'Import', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('does not have enough storage');
  await expect(dialog.getByRole('alert')).toContainText('No partial import was kept');
  await expect(page.locator('[data-context-field="dataset"] .context-field__local-badge')).toBeHidden();
});
