import { expect, test } from '@playwright/test';

test('regional indicators are read-only colorbars for every finite value with exact tooltips', async ({ page }) => {
  await page.goto('/app/?v=4&colors=anatomy&scale=linear&range=2,3');
  await expect(page.locator('.distribution-chart__bin')).toHaveCount(8);
  const finiteRows = page.locator('.region-row[data-missing="false"]');
  expect(await finiteRows.count()).toBeGreaterThan(0);
  expect(await finiteRows.locator('.region-row__track').count()).toBe(await finiteRows.count());
  await expect(page.locator('.region-row[data-missing="true"] .region-row__track')).toHaveCount(0);
  const missing = page.locator('.region-row[data-missing="true"]').first();
  await expect(missing.locator('.region-row__identity')).toHaveCSS('opacity', '0.48');
  await expect(missing.locator('.region-row__button')).toHaveAttribute('title', /no mean value available/);
  const zeroValue = page.locator('.region-row[data-region-id="-477"] .region-row__value');
  await expect(zeroValue).toHaveAttribute('title', /^mean: 0 dB rel\. V/);
  await expect(zeroValue.locator('.region-row__track')).toHaveCount(1);
  const value = page.locator('.region-row[data-region-id="-362"] .region-row__value');
  await expect(value).toHaveAttribute('title', /mean: .* dB rel\. V · below color range, clipped to lower edge/);
  const track = value.locator('.region-row__track');
  await expect(track).toHaveCSS('width', '44px');
  await expect(track).toHaveCSS('height', '3px');
  expect(await track.evaluate(node => getComputedStyle(node, '::before').backgroundImage)).toMatch(/linear-gradient/);
  expect(await track.evaluate(node => getComputedStyle(node, '::before').opacity)).toBe('0.28');
  const tick = track.locator('.region-row__tick');
  await expect(tick).toHaveCSS('width', '2px');
  await expect(tick).toHaveCSS('height', '7px');
  await expect(tick).toHaveCSS('background-color', 'rgb(68, 1, 84)');
  expect(await tick.evaluate((node) => (node as HTMLElement).style.getPropertyValue('--region-value'))).toBe('0%');
  await expect(track.locator('[role="slider"], input')).toHaveCount(0);
});

test('regional colorbars update their palette and nonlinear positions while preserving selection', async ({ page }) => {
  await page.goto('/app/?v=4&scale=linear');
  await expect(page.locator('.distribution-chart__bin')).toHaveCount(8);
  const row = page.locator('.region-row[data-region-id="-362"]');
  await row.locator('.region-row__button').click();
  const tick = row.locator('.region-row__tick');
  const initialPosition = await tick.evaluate((node) => (node as HTMLElement).style.getPropertyValue('--region-value'));
  await page.getByRole('button', { name: 'Settings' }).click();
  await page.getByLabel('Feature colormap').selectOption('cividis');
  await expect.poll(() => row.locator('.region-row__track').evaluate(node => getComputedStyle(node, '::before').backgroundImage)).toMatch(/rgb\(0, 34, 78\)/);
  await page.getByLabel('Color mapping').selectOption('pseudolog');
  await expect.poll(() => tick.evaluate((node) => (node as HTMLElement).style.getPropertyValue('--region-value'))).not.toBe(initialPosition);
  const pseudoPosition = await tick.evaluate((node) => (node as HTMLElement).style.getPropertyValue('--region-value'));
  await page.getByLabel('Color mapping').selectOption('quantile-uniform');
  await expect.poll(() => tick.evaluate((node) => (node as HTMLElement).style.getPropertyValue('--region-value'))).not.toBe(pseudoPosition);
  await expect(row).toHaveAttribute('data-selected', 'true');
  await page.goto('/app/?v=4&feature=rms_ap&repr=volume');
  await expect(page.locator('.region-statistic-domain')).toContainText('Anatomy only');
  await expect(page.locator('.region-row__track')).toHaveCount(0);
});
