import { test, expect } from '@playwright/test';

test('real AGEA coverage, masking, aggregate inspection and URL restoration', async ({ page }) => {
  await page.setViewportSize({ width: 1500, height: 1050 });
  const volumes: string[] = [];
  page.on('request', request => { if (request.url().includes('/volumes/')) volumes.push(request.url()); });
  await page.goto('/app/?lab=agea-coverage');
  await expect(page.getByRole('heading', { name: 'AGEA coverage lab' })).toBeVisible();
  await expect(page.getByRole('status')).toContainText('Ready');
  await expect(page.locator('.agea-results button')).toHaveCount(30);
  await expect(page.getByLabel('Sort experiments')).toHaveValue('source');
  expect(volumes).toHaveLength(1);
  await page.getByLabel('Search gene or experiment').fill('Slc17a7');
  await expect(page.locator('.agea-results button')).toHaveCount(2);
  await page.locator('.agea-results button').first().click();
  await expect(page.getByRole('status')).toContainText('Ready');
  await expect(page.locator('.agea-content > h2')).toContainText('Slc17a7');
  expect(volumes).toHaveLength(2);
  await page.getByRole('button', { name: 'Mask comparison', exact: true }).click();
  await expect(page.locator('.agea-views canvas')).toHaveCount(6);
  await page.getByLabel('Recompute masked color range').check();
  await page.getByLabel('coronal all measurements slice').click({ position: { x: 25, y: 30 } });
  const before = await page.locator('.agea-inspector').innerText();
  expect(new URL(page.url()).searchParams.get('voxel')).not.toBeNull();
  await page.reload();
  await expect(page.getByRole('status')).toContainText('Ready');
  await expect(page.locator('.agea-inspector')).toHaveText(before, { useInnerText: true });
  await expect(page.getByLabel('Recompute masked color range')).toBeChecked();
  await page.getByRole('button', { name: 'Across experiments', exact: true }).click();
  await expect(page.locator('.agea-legend')).toContainText('4,345');
  await expect(page.locator('.agea-views canvas')).toHaveCount(3);
  await page.getByLabel('sagittal all measurements slice').focus();
  const old = new URL(page.url()).searchParams.get('voxel');
  await page.keyboard.press('ArrowRight');
  expect(new URL(page.url()).searchParams.get('voxel')).not.toBe(old);
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download inspection report' }).click();
  expect((await download).suggestedFilename()).toMatch(/^agea-inspection-\d+\.json$/);
  await page.getByRole('button', { name: 'Coverage', exact: true }).click();
  await page.screenshot({ path: 'artifacts/agea-coverage-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect((await page.locator('.agea-views canvas').first().boundingBox())!.width).toBeGreaterThan(200);
  await page.screenshot({ path: 'artifacts/agea-coverage-mobile.png', fullPage: true });
});

test('failed or superseded gene requests never leave stale expression visible', async ({ page }) => {
  await page.goto('/app/?lab=agea-coverage');
  await expect(page.getByRole('status')).toContainText('Ready');
  await page.route('**/volumes/*.bin.gz', route => route.fulfill({ body: Buffer.from('corrupt'), status: 200 }));
  await page.getByLabel('Search gene or experiment').fill('Slc17a7');
  await page.locator('.agea-results button').first().click();
  await expect(page.getByRole('status')).toContainText('Volume unavailable');
  await expect(page.locator('.agea-inspector')).toContainText('Expression loading or unavailable');
  await page.unroute('**/volumes/*.bin.gz');
  await page.locator('.agea-results button').first().click();
  await expect(page.getByRole('status')).toContainText('Ready');
  await page.getByLabel('Search gene or experiment').fill('Grik');
  await page.route('**/volumes/*.bin.gz', async route => { await new Promise(resolve => setTimeout(resolve, 200)); await route.continue(); });
  await page.locator('.agea-results button').first().click();
  await page.getByLabel('Search gene or experiment').fill('Slc17a7');
  await page.locator('.agea-results button').first().click();
  await expect(page.getByRole('status')).toContainText('Ready');
  await expect(page.locator('.agea-content > h2')).toContainText('Slc17a7');
  await expect(page.locator('.agea-inspector')).not.toContainText('Expression loading or unavailable');
});
