import manifestRaw from './manifest.json?raw';
import allenUrl from './allen.bin?url';
import berylUrl from './beryl.bin?url';
import cosmosUrl from './cosmos.bin?url';

/** Generated by tools/projection_pack/build_region_navigation.py. */
export const REGION_NAVIGATION_ASSETS = {
  manifest: JSON.parse(manifestRaw) as unknown,
  resources: { allen: allenUrl, beryl: berylUrl, cosmos: cosmosUrl },
};
