import { defineConfig } from '@playwright/test';

import browserConfig from './playwright.config';

export default defineConfig({
  ...browserConfig,
  workers: 1,
  projects: [
    { name: 'chromium', use: { browserName: 'chromium' } },
    {
      name: 'firefox',
      use: { browserName: 'firefox' },
      // Headless Firefox has no WebGL driver in the Linux gate environment.
      // Native GPU-backed Firefox remains part of owner release QA.
      grepInvert: /retained 3-D lab|3-D viewport deactivates|3-D picking|failed upgrade|3-D context lazily|3-D shares presentation|volume mode keeps integrated/,
    },
    {
      name: 'webkit',
      use: { browserName: 'webkit' },
      // Playwright's Linux WebKit port cannot persist Blob/File values in
      // IndexedDB. Native Safari local-import coverage is run separately.
      grepInvert: /quota failure after queued resource writes|validated ZIP preview is read-only|duplicate immutable local releases|bundle generated by the public regional authoring API|public-authored synthetic volume|deleting the active local release|active local deletion falls back|sharing a local view|local manager reports exact releases|legacy local rows and unavailable Storage API/,
    },
  ],
});
